export const LocalStorageKey = {
  ACCESS_TOKEN: 'ACCESS_TOKEN',
  ALGORITHM: 'ALGORITHM',
  DATASET: 'DATASET',
  REMEMBERED_EMAIL: 'REMEMBERED_EMAIL',
  REMEMBERED_PASSWORD: 'REMEMBERED_PASSWORD',
};
