export enum GlobalErrorCode {
  BAD_REQUEST = 'BAD_REQUEST',
  JWT_EXPIRED = 'JWT_EXPIRED',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  EMAIL_DUPLICATED = 'EMAIL_DUPLICATED',
  EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND',
}
