# name: Build Application

# on:
#   workflow_call:
#     inputs:
#       environment-name:
#         description: "The name of the GitHub environment to use as context for this workflow"
#         required: true
#         type: string
#       source_branch:
#         description: "Branch to merge from"
#         required: false
#         type: string
#         default: ""

# jobs:
#   build-frontend:
#     environment:
#       name: ${{ inputs.environment-name }}
#     runs-on: ubuntu-22.04
#     name: Build Frontend App
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v6
#         with:
#           ref: ${{ inputs.source_branch }}

#       - name: Use Node.js
#         uses: actions/setup-node@v6
#         with:
#           node-version: 24
#           cache: "npm"
#           cache-dependency-path: package-lock.json

#       - name: Install dependencies
#         run: npm ci

#       - name: Build frontend
#         run: npm run build
