name: Release Application

on:
  workflow_call:

jobs:
  release-frontend:
    name: Release Frontend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Write .env file
        run: |
          cat <<EOF > .env
          VITE_BACKEND_URL="https://api.courserecom.site"
          EOF

      - name: Print env
        run: cat .env

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun ci

      - name: Build
        run: bun run build
      
      - name: Copy static web app config
        run: cp staticwebapp.config.json dist/

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/dist"
          output_location: ""
          skip_app_build: true
